In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt

In [2]:
df_category = pd.read_csv('category.csv')
df_customers = pd.read_csv('customers.csv')
df_geolocation = pd.read_csv('geolocation.csv')
df_order_items = pd.read_csv('order_items.csv')
df_order_payments = pd.read_csv('order_payments.csv')
df_order_reviews = pd.read_csv('order_reviews.csv')
df_products = pd.read_csv('products.csv')
df_sellers = pd.read_csv('sellers.csv')
df_treino = pd.read_csv('treino.csv')
df_teste = pd.read_csv('teste_kaggle.csv')

In [3]:
df_teste

,order_id,customer_id,order_purchase_timestamp,order_approved_at
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29
...,...,...,...,...
28147,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10
28148,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54
28149,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03
28150,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51
28151,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29

In [4]:
df = df_teste.merge(df_customers)
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,e017db36909fc33b589b0570c068a574,17505,marilia,sao paulo
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,8be0275a7f9336dee5b2cf2f8e6158e5,27123,barra do pirai,RJ
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,67798c2a2ad8d90cedd7146e3ef9335a,16370,promissao,NaN
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,e965a5500443e3e4746a2230aff2f1db,95900,lajeado,RS
...,...,...,...,...,...,...,...,...
28147,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,785350657e82cd7e13ba1e6a82bb62ab,92500,NaN,NaN
28148,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,e21bea57967ffc7bdc8b07558e09685e,22750,NaN,NaN
28149,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,a7408d5a8aaa865315db143d43030537,88060,florianopolis,SC
28150,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,0b7604941dd811e84ae22ca3b90a49ff,11320,SAO VICENTE,SP
28151,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF

In [5]:
df_geolocation_c = df_geolocation.rename(columns={
    'geolocation_zip_code_prefix': 'customer_zip_code_prefix',
    'geolocation_lat': 'geolocation_lat_c',
    'geolocation_lng': 'geolocation_lng_c',
    'geolocation_city': 'geolocation_city_c',
    'geolocation_state': 'geolocation_state_c'
})

df_geolocation_s = df_geolocation.rename(columns={
    'geolocation_zip_code_prefix': 'seller_zip_code_prefix',
    'geolocation_lat': 'geolocation_lat_s',
    'geolocation_lng': 'geolocation_lng_s',
    'geolocation_city': 'geolocation_city_s',
    'geolocation_state': 'geolocation_state_s'
})

In [6]:
df_geolocation_c = df_geolocation_c.drop_duplicates()
df = df.merge(df_geolocation_c, on='customer_zip_code_prefix', how='left')
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.178366,-51.177477,caxias do sul,RS
1,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.180213,-51.175305,caxias do sul,RS
2,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.180560,-51.181948,caxias do sul,RS
3,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.175190,-51.170404,caxias do sul,RS
4,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.175191,-51.170379,caxias do sul,RS
...,...,...,...,...,...,...,...,...,...,...,...,...
2853116,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.886606,-48.107832,brasilia,DF
2853117,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.880746,-48.097769,brasília,DF
2853118,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.879448,-48.095622,brasilia,DF
2853119,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.891730,-48.118213,brasilia,DF
2853120,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.881275,-48.097859,brasilia,DF

In [7]:
df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c,payment_sequential,payment_type,payment_installments,payment_value
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.178366,-51.177477,caxias do sul,RS,1,credit_card,2,144.31
1,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.180213,-51.175305,caxias do sul,RS,1,credit_card,2,144.31
2,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.180560,-51.181948,caxias do sul,RS,1,credit_card,2,144.31
3,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.175190,-51.170404,caxias do sul,RS,1,credit_card,2,144.31
4,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,a35ac27a1a672396d8cf0053bc1e8f69,95082,CAXIAS DO SUL,RS,-29.175191,-51.170379,caxias do sul,RS,1,credit_card,2,144.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853116,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.886606,-48.107832,brasilia,DF,1,credit_card,1,43.29
2853117,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.880746,-48.097769,brasília,DF,1,credit_card,1,43.29
2853118,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.879448,-48.095622,brasilia,DF,1,credit_card,1,43.29
2853119,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.891730,-48.118213,brasilia,DF,1,credit_card,1,43.29
2853120,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,c7fb005dfaed077788b1da6313ee6688,72301,brasilia,DF,-15.881275,-48.097859,brasilia,DF,1,credit_card,1,43.29

In [8]:
#base de sellers
df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')
df2

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR
...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,88303,itajai,SC
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1206,sao paulo,SP
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,80610,curitiba,PR
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,4733,sao paulo,SP
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,14940,ibitinga,SP

In [9]:
df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')
df2

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,88303,itajai,SC,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1206,sao paulo,SP,informatica_acessorios,31.0,232.0,1.0,8950.0,45.0,26.0,38.0
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,80610,curitiba,PR,esporte_lazer,43.0,869.0,1.0,967.0,21.0,24.0,19.0
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,4733,sao paulo,SP,informatica_acessorios,56.0,1306.0,1.0,100.0,20.0,20.0,20.0
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,14940,ibitinga,SP,cama_mesa_banho,47.0,511.0,1.0,600.0,30.0,3.0,19.0

In [10]:
df_geolocation_s = df_geolocation_s.drop_duplicates()
df2 = df2.merge(df_geolocation_s, on='seller_zip_code_prefix', how='left')
df2

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,598.0,4.0,650.0,28.0,9.0,14.0,-22.498183,-44.123614,volta redonda,RJ
1,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,598.0,4.0,650.0,28.0,9.0,14.0,-22.487885,-44.131566,volta redonda,RJ
2,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,598.0,4.0,650.0,28.0,9.0,14.0,-22.501227,-44.132443,volta redonda,RJ
3,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,598.0,4.0,650.0,28.0,9.0,14.0,-22.500389,-44.124773,volta redonda,RJ
4,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,27277,volta redonda,SP,...,598.0,4.0,650.0,28.0,9.0,14.0,-22.499963,-44.127571,volta redonda,RJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250769,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,14940,ibitinga,SP,...,511.0,1.0,600.0,30.0,3.0,19.0,-21.760866,-48.820339,ibitinga,SP
12250770,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,14940,ibitinga,SP,...,511.0,1.0,600.0,30.0,3.0,19.0,-21.758844,-48.826249,ibitinga,SP
12250771,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,14940,ibitinga,SP,...,511.0,1.0,600.0,30.0,3.0,19.0,-21.765902,-48.824481,ibitinga,SP
12250772,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,14940,ibitinga,SP,...,511.0,1.0,600.0,30.0,3.0,19.0,-21.760676,-48.847655,ibitinga,SP
12250773,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,14940,ibitinga,SP,...,511.0,1.0,600.0,30.0,3.0,19.0,-21.754867,-48.838906,ibitinga,SP

In [11]:
df = df.drop_duplicates()
df2 = df2.drop_duplicates()

In [12]:
df.drop(columns=[
    'customer_unique_id',
    'customer_city',
    'customer_state',
    'payment_sequential',
    'payment_type',
    'payment_installments'
], inplace=True)
df.drop_duplicates(subset=['order_id', 'payment_value'], keep='first', inplace=True)
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c,payment_value
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,-29.178366,-51.177477,caxias do sul,RS,144.31
38,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,-22.202558,-49.965560,marilia,SP,62.00
83,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,-22.468842,-43.826934,barra do piraí,RJ,133.47
126,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,-21.533431,-49.854538,promissao,SP,83.79
376,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,-29.459579,-51.967684,lajeado,RS,164.80
...,...,...,...,...,...,...,...,...,...,...
2852240,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,-30.110826,-51.363767,guaiba,RS,36.94
2852613,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,-22.947654,-43.338606,rio de janeiro,RJ,199.00
2852753,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,-27.482572,-48.409721,florianopolis,SC,123.69
2852854,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,-23.972425,-46.371265,sao vicente,SP,714.35
2853101,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,-15.887367,-48.110117,brasilia,DF,43.29

In [13]:
df2.drop_duplicates(subset=['order_id', 'order_item_id', 'product_id'], keep='first', inplace=True)
pd.set_option('display.max_columns', None)
display(df2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,-22.498183,-44.123614,volta redonda,RJ
45,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,-23.566258,-46.518417,sao paulo,SP
75,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,-22.264094,-46.158564,borda da mata,MG
136,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,-20.548228,-47.395897,franca,SP
462,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,-22.931427,-53.133759,loanda,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250210,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,88303,itajai,SC,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0,-26.912429,-48.677381,itajai,SC
12250357,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1206,sao paulo,SP,informatica_acessorios,31.0,232.0,1.0,8950.0,45.0,26.0,38.0,-23.535536,-46.643052,Sao Paulo,SP
12250379,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,80610,curitiba,PR,esporte_lazer,43.0,869.0,1.0,967.0,21.0,24.0,19.0,-25.469214,-49.293935,curitiba,PR
12250519,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,4733,sao paulo,SP,informatica_acessorios,56.0,1306.0,1.0,100.0,20.0,20.0,20.0,-23.636657,-46.694780,são paulo,SP
12250527,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,14940,ibitinga,SP,cama_mesa_banho,47.0,511.0,1.0,600.0,30.0,3.0,19.0,-21.766477,-48.831547,ibitinga,SP

In [14]:
df2.drop(columns=[
    'price',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty'
], inplace=True)
display(df2)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,13.29,27277,volta redonda,SP,cool_stuff,650.0,28.0,9.0,14.0,-22.498183,-44.123614,volta redonda,RJ
45,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,19.93,3471,sao paulo,SP,pet_shop,30000.0,50.0,30.0,40.0,-23.566258,-46.518417,sao paulo,SP
75,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,17.87,37564,borda da mata,MG,moveis_decoracao,3050.0,33.0,13.0,33.0,-22.264094,-46.158564,borda da mata,MG
136,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.79,14403,franca,SP,perfumaria,200.0,16.0,10.0,15.0,-20.548228,-47.395897,franca,SP
462,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,18.14,87900,loanda,PR,ferramentas_jardim,3750.0,35.0,40.0,30.0,-22.931427,-53.133759,loanda,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12250210,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,43.41,88303,itajai,SC,utilidades_domesticas,10150.0,89.0,15.0,40.0,-26.912429,-48.677381,itajai,SC
12250357,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,36.53,1206,sao paulo,SP,informatica_acessorios,8950.0,45.0,26.0,38.0,-23.535536,-46.643052,Sao Paulo,SP
12250379,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,16.95,80610,curitiba,PR,esporte_lazer,967.0,21.0,24.0,19.0,-25.469214,-49.293935,curitiba,PR
12250519,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,8.72,4733,sao paulo,SP,informatica_acessorios,100.0,20.0,20.0,20.0,-23.636657,-46.694780,são paulo,SP
12250527,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,12.79,14940,ibitinga,SP,cama_mesa_banho,600.0,30.0,3.0,19.0,-21.766477,-48.831547,ibitinga,SP

In [15]:
df_final = df.merge(df2, on='order_id', how='left')
display(df_final)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,-29.178366,-51.177477,caxias do sul,RS,144.31,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-05-07 15:24:08,25.31,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,-20.944706,-45.827098,ilicinea,MG
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,-22.202558,-49.965560,marilia,SP,62.00,1,5403528d987ad26e8d7cb25940411987,6560211a19b47992c3666cc44a7e94c0,2018-06-18 16:31:30,13.00,5849,sao paulo,SP,relogios_presentes,250.0,16.0,2.0,11.0,-23.651115,-46.755211,sao paulo,SP
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,-22.468842,-43.826934,barra do piraí,RJ,133.47,1,283dc451ad3918badb976d56ff887289,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-23 13:42:15,23.57,13405,piracicaba,SP,cama_mesa_banho,1650.0,44.0,2.0,35.0,-22.716839,-47.657366,piracicaba,SP
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,-21.533431,-49.854538,promissao,SP,83.79,1,af893b2efa430418d774a852e7870601,8a432f4e5b471f8da497d7dc517666e2,2018-08-10 03:15:23,14.79,19042,presidente prudente,SP,utilidades_domesticas,1550.0,29.0,17.0,23.0,-22.133927,-51.368753,presidente prudente,SP
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,-29.459579,-51.967684,lajeado,RS,164.80,1,6f3b5b605d91b7439c5e3f5a8dffeea7,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-02 15:30:29,18.90,14840,guariba,SP,relogios_presentes,335.0,17.0,11.0,16.0,-21.362358,-48.232976,guariba,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32076,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,-30.110826,-51.363767,guaiba,RS,36.94,1,94a6c010ef78e62cab34c6caf0a69b5f,080102cd0a76b09e0dcf55fcacc60e05,2018-08-07 18:45:10,19.04,31140,belo horizonte,MG,consoles_games,100.0,20.0,3.0,15.0,-19.892339,-43.932620,belo horizonte,MG
32077,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,-22.947654,-43.338606,rio de janeiro,RJ,199.00,1,7a10781637204d8d10485c71a6108a2e,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-04 13:30:47,0.00,14840,guariba,SP,relogios_presentes,342.0,18.0,13.0,15.0,-21.362358,-48.232976,guariba,SP
32078,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,-27.482572,-48.409721,florianopolis,SC,123.69,1,2ff995aead9c63a1f37a07b3664ead37,8b9d6eec4a7eb7d0f9d579ce0b38324d,2018-05-18 13:57:03,34.69,26562,mesquita,RJ,moveis_sala,7500.0,61.0,11.0,46.0,-22.767225,-43.424453,mesquita,RJ
32079,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,-23.972425,-46.371265,sao vicente,SP,714.35,1,26abb7e42cded69ba9b3736643ebeb39,4869f7a5dfa277a7dca6462dcf3b52b2,2018-06-22 04:16:51,18.45,14840,guariba,SP,relogios_presentes,867.0,20.0,7.0,14.0,-21.362358,-48.232976,guariba,SP
32080,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,-15.887367,-48.110117,brasilia,DF,43.29,1,6157bc1be1e8edc531fc0c94dddf5ac9,ea8482cd71df3c1969d7b9473ff13abc,2018-08-06 21:45:29,15.30,4160,sao paulo,SP,telefonia,300.0,17.0,4.0,12.0,-23.623582,-46.610560,sao paulo,SP

In [16]:
df_final.to_csv('Base_Teste_Consolidada.csv', index=False)

In [17]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32081 entries, 0 to 32080
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  32081 non-null  object
 1   customer_id               32081 non-null  object
 2   order_purchase_timestamp  32081 non-null  object
 3   order_approved_at         32081 non-null  object
 4   customer_zip_code_prefix  32081 non-null  int64
 5   geolocation_lat_c         31986 non-null  float64
 6   geolocation_lng_c         31986 non-null  float64
 7   geolocation_city_c        31986 non-null  object
 8   geolocation_state_c       31986 non-null  object
 9   payment_value             32081 non-null  float64
 10  order_item_id             32081 non-null  int64
 11  product_id                32081 non-null  object
 12  seller_id                 32081 non-null  object
 13  shipping_limit_date       32081 non-null  object
 14  freight_value             31771 non-null  float64
 15  seller_zip_code_prefix    32081 non-null  int64
 16  seller_city               32081 non-null  object
 17  seller_state              32081 non-null  object
 18  product_category_name     31917 non-null  object
 19  product_weight_g          32081 non-null  float64
 20  product_length_cm         32081 non-null  float64
 21  product_height_cm         32081 non-null  float64
 22  product_width_cm          32081 non-null  float64
 23  geolocation_lat_s         32032 non-null  float64
 24  geolocation_lng_s         32032 non-null  float64
 25  geolocation_city_s        32032 non-null  object
 26  geolocation_state_s       32032 non-null  object
dtypes: float64(10), int64(3), object(14)
memory usage: 6.6+ MB