In [25]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt

In [26]:
df_category = pd.read_csv('category.csv')
df_customers = pd.read_csv('customers.csv')
df_geolocation = pd.read_csv('geolocation.csv')
df_order_items = pd.read_csv('order_items.csv')
df_order_payments = pd.read_csv('order_payments.csv')
df_order_reviews = pd.read_csv('order_reviews.csv')
df_products = pd.read_csv('products.csv')
df_sellers = pd.read_csv('sellers.csv')
df_treino = pd.read_csv('treino.csv')
df_teste = pd.read_csv('teste_kaggle.csv')

In [27]:
df = df_teste.merge(df_customers)

df_geolocation_c = df_geolocation.rename(columns={
    'geolocation_zip_code_prefix': 'customer_zip_code_prefix',
    'geolocation_lat': 'geolocation_lat_c',
    'geolocation_lng': 'geolocation_lng_c',
    'geolocation_city': 'geolocation_city_c',
    'geolocation_state': 'geolocation_state_c'
})

df_geolocation_s = df_geolocation.rename(columns={
    'geolocation_zip_code_prefix': 'seller_zip_code_prefix',
    'geolocation_lat': 'geolocation_lat_s',
    'geolocation_lng': 'geolocation_lng_s',
    'geolocation_city': 'geolocation_city_s',
    'geolocation_state': 'geolocation_state_s'
})


df_geolocation_c = df_geolocation_c.drop_duplicates()
df = df.merge(df_geolocation_c, on='customer_zip_code_prefix', how='left')

df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')

df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')

df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')

df_geolocation_s = df_geolocation_s.drop_duplicates()
df2 = df2.merge(df_geolocation_s, on='seller_zip_code_prefix', how='left')

df = df.drop_duplicates()
df2 = df2.drop_duplicates()

df.drop(columns=[
    'customer_unique_id',
    'customer_city',
    'customer_state',
    'payment_sequential',
    'payment_type',
    'payment_installments'
], inplace=True)
df.drop_duplicates(subset=['order_id', 'payment_value'], keep='first', inplace=True)

df2.drop_duplicates(subset=['order_id', 'order_item_id', 'product_id'], keep='first', inplace=True)

df2.drop(columns=[
    'price',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty'
], inplace=True)

df_final = df.merge(df2, on='order_id', how='left')

pd.set_option('display.max_columns', None)
display(df_final)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,-29.178366,-51.177477,caxias do sul,RS,144.31,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-05-07 15:24:08,25.31,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,-20.944706,-45.827098,ilicinea,MG
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,-22.202558,-49.965560,marilia,SP,62.00,1,5403528d987ad26e8d7cb25940411987,6560211a19b47992c3666cc44a7e94c0,2018-06-18 16:31:30,13.00,5849,sao paulo,SP,relogios_presentes,250.0,16.0,2.0,11.0,-23.651115,-46.755211,sao paulo,SP
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,-22.468842,-43.826934,barra do piraí,RJ,133.47,1,283dc451ad3918badb976d56ff887289,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-23 13:42:15,23.57,13405,piracicaba,SP,cama_mesa_banho,1650.0,44.0,2.0,35.0,-22.716839,-47.657366,piracicaba,SP
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,-21.533431,-49.854538,promissao,SP,83.79,1,af893b2efa430418d774a852e7870601,8a432f4e5b471f8da497d7dc517666e2,2018-08-10 03:15:23,14.79,19042,presidente prudente,SP,utilidades_domesticas,1550.0,29.0,17.0,23.0,-22.133927,-51.368753,presidente prudente,SP
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,-29.459579,-51.967684,lajeado,RS,164.80,1,6f3b5b605d91b7439c5e3f5a8dffeea7,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-02 15:30:29,18.90,14840,guariba,SP,relogios_presentes,335.0,17.0,11.0,16.0,-21.362358,-48.232976,guariba,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32076,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,-30.110826,-51.363767,guaiba,RS,36.94,1,94a6c010ef78e62cab34c6caf0a69b5f,080102cd0a76b09e0dcf55fcacc60e05,2018-08-07 18:45:10,19.04,31140,belo horizonte,MG,consoles_games,100.0,20.0,3.0,15.0,-19.892339,-43.932620,belo horizonte,MG
32077,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,-22.947654,-43.338606,rio de janeiro,RJ,199.00,1,7a10781637204d8d10485c71a6108a2e,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-04 13:30:47,0.00,14840,guariba,SP,relogios_presentes,342.0,18.0,13.0,15.0,-21.362358,-48.232976,guariba,SP
32078,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,-27.482572,-48.409721,florianopolis,SC,123.69,1,2ff995aead9c63a1f37a07b3664ead37,8b9d6eec4a7eb7d0f9d579ce0b38324d,2018-05-18 13:57:03,34.69,26562,mesquita,RJ,moveis_sala,7500.0,61.0,11.0,46.0,-22.767225,-43.424453,mesquita,RJ
32079,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,-23.972425,-46.371265,sao vicente,SP,714.35,1,26abb7e42cded69ba9b3736643ebeb39,4869f7a5dfa277a7dca6462dcf3b52b2,2018-06-22 04:16:51,18.45,14840,guariba,SP,relogios_presentes,867.0,20.0,7.0,14.0,-21.362358,-48.232976,guariba,SP
32080,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,-15.887367,-48.110117,brasilia,DF,43.29,1,6157bc1be1e8edc531fc0c94dddf5ac9,ea8482cd71df3c1969d7b9473ff13abc,2018-08-06 21:45:29,15.30,4160,sao paulo,SP,telefonia,300.0,17.0,4.0,12.0,-23.623582,-46.610560,sao paulo,SP

In [28]:
df_final.to_csv('Base_Teste_Consolidada.csv', index=False)

In [29]:
df = pd.read_csv('Base_Teste_Consolidada.csv')

In [30]:
df['product_volume'] = df['product_length_cm']*df['product_height_cm']*df['product_width_cm']

# Função para calcular a distância usando a fórmula de Haversine
def calcular_distancia(lat1, lon1, lat2, lon2):
    # Converter as coordenadas de graus para radianos
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    # Diferenças das coordenadas
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Fórmula de Haversine
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    # Raio da Terra em quilômetros
    raio_terra_km = 6371
    distancia = raio_terra_km * c
    return distancia

# Aplicar a função ao DataFrame para criar a nova coluna com as distâncias
df['distancia_km'] = df.apply(lambda row: calcular_distancia(row['geolocation_lat_c'], row['geolocation_lng_c'], row['geolocation_lat_s'], row['geolocation_lng_s']), axis=1)
df = df.drop(columns=['geolocation_lat_c', 'geolocation_lng_c', 'geolocation_lat_s', 'geolocation_lng_s'])

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['purchase_to_approval_minutes'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.total_seconds() / 86400

# Dicionário de substituições para padronizar variações de nomes comuns
substituicoes = {
    "sp": "sao paulo",
    "sao paulo": "sao paulo",
    "so paulo": "sao paulo",
    "Sao paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "são paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "varzea paulista": "varzea paulista"
    # Adicione outras variações de cidade aqui, se necessário
}

# Função para aplicar as substituições específicas
def padronizar_cidade(nome):
    return substituicoes.get(nome, nome)  # Substitui se a cidade estiver no dicionário, caso contrário, mantém o original

# Aplicando a normalização e padronização nas colunas de cidades
df['geolocation_city_c'] = df['geolocation_city_c'].apply(padronizar_cidade)
df['geolocation_city_s'] = df['geolocation_city_s'].apply(padronizar_cidade)

pd.set_option('display.max_columns', None)
display(df)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,caxias do sul,RS,144.31,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-05-07 15:24:08,25.31,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,1061.973738,0.027801
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,marilia,SP,62.00,1,5403528d987ad26e8d7cb25940411987,6560211a19b47992c3666cc44a7e94c0,2018-06-18 16:31:30,13.00,5849,sao paulo,SP,relogios_presentes,250.0,16.0,2.0,11.0,sao paulo,SP,352.0,366.092752,0.019734
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,barra do piraí,RJ,133.47,1,283dc451ad3918badb976d56ff887289,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-23 13:42:15,23.57,13405,piracicaba,SP,cama_mesa_banho,1650.0,44.0,2.0,35.0,piracicaba,SP,3080.0,394.192807,0.009271
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,promissao,SP,83.79,1,af893b2efa430418d774a852e7870601,8a432f4e5b471f8da497d7dc517666e2,2018-08-10 03:15:23,14.79,19042,presidente prudente,SP,utilidades_domesticas,1550.0,29.0,17.0,23.0,presidente prudente,SP,11339.0,169.959350,0.683519
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,lajeado,RS,164.80,1,6f3b5b605d91b7439c5e3f5a8dffeea7,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-02 15:30:29,18.90,14840,guariba,SP,relogios_presentes,335.0,17.0,11.0,16.0,guariba,SP,2992.0,975.175056,0.007188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32076,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,guaiba,RS,36.94,1,94a6c010ef78e62cab34c6caf0a69b5f,080102cd0a76b09e0dcf55fcacc60e05,2018-08-07 18:45:10,19.04,31140,belo horizonte,MG,consoles_games,100.0,20.0,3.0,15.0,belo horizonte,MG,900.0,1359.877613,0.009491
32077,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,rio de janeiro,RJ,199.00,1,7a10781637204d8d10485c71a6108a2e,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-04 13:30:47,0.00,14840,guariba,SP,relogios_presentes,342.0,18.0,13.0,15.0,guariba,SP,3510.0,533.938834,0.648229
32078,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,florianopolis,SC,123.69,1,2ff995aead9c63a1f37a07b3664ead37,8b9d6eec4a7eb7d0f9d579ce0b38324d,2018-05-18 13:57:03,34.69,26562,mesquita,RJ,moveis_sala,7500.0,61.0,11.0,46.0,mesquita,RJ,30866.0,725.631189,0.011910
32079,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,sao vicente,SP,714.35,1,26abb7e42cded69ba9b3736643ebeb39,4869f7a5dfa277a7dca6462dcf3b52b2,2018-06-22 04:16:51,18.45,14840,guariba,SP,relogios_presentes,867.0,20.0,7.0,14.0,guariba,SP,1960.0,347.434673,2.268912
32080,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,brasilia,DF,43.29,1,6157bc1be1e8edc531fc0c94dddf5ac9,ea8482cd71df3c1969d7b9473ff13abc,2018-08-06 21:45:29,15.30,4160,sao paulo,SP,telefonia,300.0,17.0,4.0,12.0,sao paulo,SP,816.0,874.394957,0.008507

In [31]:
df.to_csv('FBase_Teste_Consolidada.csv', index=False)

In [32]:
df = df_treino.merge(df_customers)


df_geolocation_c = df_geolocation_c.drop_duplicates()
df = df.merge(df_geolocation_c, on='customer_zip_code_prefix', how='left')

df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')

df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')

df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')

df_geolocation_s = df_geolocation_s.drop_duplicates()
df2 = df2.merge(df_geolocation_s, on='seller_zip_code_prefix', how='left')

df = df.drop_duplicates()
df2 = df2.drop_duplicates()

df.drop(columns=[
    'customer_unique_id',
    'customer_city',
    'customer_state',
    'payment_sequential',
    'payment_type',
    'payment_installments'
], inplace=True)
df.drop_duplicates(subset=['order_id', 'payment_value'], keep='first', inplace=True)

df2.drop_duplicates(subset=['order_id', 'order_item_id', 'product_id'], keep='first', inplace=True)

df2.drop(columns=[
    'price',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty'
], inplace=True)

df_final = df.merge(df2, on='order_id', how='left')

pd.set_option('display.max_columns', None)
display(df_final)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days),customer_zip_code_prefix,geolocation_lat_c,geolocation_lng_c,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_lat_s,geolocation_lng_s,geolocation_city_s,geolocation_state_s
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,8.44,15.54,3149,-23.574809,-46.587471,SP,SP,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,8.72,9350,maua,SP,utilidades_domesticas,500.0,19.0,8.0,13.0,-23.680114,-46.452454,maua,SP
1,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,13.21,26.19,59296,-5.767733,-35.275467,sao goncalo do amarante,RN,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,27.20,31842,belo horizonte,MG,pet_shop,450.0,30.0,10.0,20.0,-19.840168,-43.923299,belo horizonte,MG
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2.87,12.11,9195,-23.675037,-46.524784,santo andre,SP,28.62,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,8.72,8752,mogi das cruzes,SP,papelaria,250.0,51.0,15.0,15.0,-23.551707,-46.260979,mogi das cruzes,SP
3,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,16.54,22.09,86320,-23.548581,-50.550660,congonhinhas,PR,175.26,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,27.36,7112,guarulhos,SP,automotivo,7150.0,65.0,10.0,65.0,-23.465304,-46.511487,guarulhos,SP
4,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,9.99,21.45,26525,-22.800936,-43.424861,nilopolis,RJ,75.16,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,15.17,12940,atibaia,SP,automotivo,50.0,16.0,16.0,17.0,-23.112774,-46.548885,atibaia,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78110,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,22.19,23.46,11722,-24.001467,-46.446355,praia grande,SP,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,20.10,17602,tupa,SP,bebes,4950.0,40.0,10.0,40.0,-21.935321,-50.497562,tupa,SP
78111,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,24.86,30.38,45920,-17.891522,-39.370942,nova vicosa,BA,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,65.02,8290,sao paulo,SP,eletrodomesticos_2,13300.0,32.0,90.0,22.0,-23.551013,-46.448489,sao paulo,SP
78112,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,-22.555985,-42.690761,japuiba,RJ,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,-20.944706,-45.827098,ilicinea,MG
78113,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,-22.555985,-42.690761,japuiba,RJ,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,-20.944706,-45.827098,ilicinea,MG
78114,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,7.67,25.13,83750,-25.775722,-49.723981,lapa,PR,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,18.36,14407,franca,SP,beleza_saude,150.0,16.0,7.0,15.0,-20.502342,-47.421590,franca,SP

In [33]:
df_final.to_csv('Base_Treino_Consolidada.csv', index=False)

In [34]:
df = pd.read_csv('Base_Treino_Consolidada.csv')

In [35]:
df['product_volume'] = df['product_length_cm']*df['product_height_cm']*df['product_width_cm']

# Função para calcular a distância usando a fórmula de Haversine
def calcular_distancia(lat1, lon1, lat2, lon2):
    # Converter as coordenadas de graus para radianos
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    # Diferenças das coordenadas
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Fórmula de Haversine
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    # Raio da Terra em quilômetros
    raio_terra_km = 6371
    distancia = raio_terra_km * c
    return distancia

# Aplicar a função ao DataFrame para criar a nova coluna com as distâncias
df['distancia_km'] = df.apply(lambda row: calcular_distancia(row['geolocation_lat_c'], row['geolocation_lng_c'], row['geolocation_lat_s'], row['geolocation_lng_s']), axis=1)
df = df.drop(columns=['geolocation_lat_c', 'geolocation_lng_c', 'geolocation_lat_s', 'geolocation_lng_s'])

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_delivered_carrier_date'] = pd.to_datetime(df['order_delivered_carrier_date'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['purchase_to_approval_minutes'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.total_seconds() / 86400
df['approval_to_carrier_days'] = (df['order_delivered_carrier_date'] - df['order_approved_at']).dt.total_seconds() / 86400
df['carrier_to_customer_days'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.total_seconds() / 86400

# Dicionário de substituições para padronizar variações de nomes comuns
substituicoes = {
    "sp": "sao paulo",
    "sao paulo": "sao paulo",
    "so paulo": "sao paulo",
    "Sao paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "são paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "varzea paulista": "varzea paulista"
    # Adicione outras variações de cidade aqui, se necessário
}

# Função para aplicar as substituições específicas
def padronizar_cidade(nome):
    return substituicoes.get(nome, nome)  # Substitui se a cidade estiver no dicionário, caso contrário, mantém o original

# Aplicando a normalização e padronização nas colunas de cidades
df['geolocation_city_c'] = df['geolocation_city_c'].apply(padronizar_cidade)
df['geolocation_city_s'] = df['geolocation_city_s'].apply(padronizar_cidade)

pd.set_option('display.max_columns', None)
display(df)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days),customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes,approval_to_carrier_days,carrier_to_customer_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,8.44,15.54,3149,SP,SP,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,8.72,9350,maua,SP,utilidades_domesticas,500.0,19.0,8.0,13.0,maua,SP,1976.0,18.063837,0.007431,2.366493,6.062650
1,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,13.21,26.19,59296,sao goncalo do amarante,RN,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,27.20,31842,belo horizonte,MG,pet_shop,450.0,30.0,10.0,20.0,belo horizonte,MG,6000.0,1822.800366,0.012419,3.745833,9.450498
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2.87,12.11,9195,santo andre,SP,28.62,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,8.72,8752,mogi das cruzes,SP,papelaria,250.0,51.0,15.0,15.0,mogi das cruzes,SP,11475.0,30.174037,0.042940,0.893113,1.937824
3,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,16.54,22.09,86320,congonhinhas,PR,175.26,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,27.36,7112,guarulhos,SP,automotivo,7150.0,65.0,10.0,65.0,guarulhos,SP,42250.0,411.952997,0.009120,1.699896,14.833229
4,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,9.99,21.45,26525,nilopolis,RJ,75.16,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,15.17,12940,atibaia,SP,automotivo,50.0,16.0,16.0,17.0,atibaia,SP,4352.0,321.730402,0.008113,5.864988,4.116725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78110,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,22.19,23.46,11722,praia grande,SP,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,20.10,17602,tupa,SP,bebes,4950.0,40.0,10.0,40.0,tupa,SP,16000.0,474.098245,0.008090,1.425058,20.760579
78111,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,24.86,30.38,45920,nova vicosa,BA,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,65.02,8290,sao paulo,SP,eletrodomesticos_2,13300.0,32.0,90.0,22.0,sao paulo,SP,63360.0,968.051192,0.012188,1.241782,23.605451
78112,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,japuiba,RJ,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,370.146853,0.005486,3.749097,13.331840
78113,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,japuiba,RJ,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,370.146853,0.005486,3.749097,13.331840
78114,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,7.67,25.13,83750,lapa,PR,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,18.36,14407,franca,SP,beleza_saude,150.0,16.0,7.0,15.0,franca,SP,1680.0,631.817784,0.599282,0.452442,6.622581

In [36]:
df.to_csv('FBase_Treino_Consolidada.csv', index=False)