In [24]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt

In [25]:
df_treino = pd.read_csv('FBase_Treino_Consolidada.csv')

In [26]:
pd.set_option('display.max_columns', None)
display(df_treino)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days),customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes,approval_to_carrier_days,carrier_to_customer_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,8.44,15.54,3149,SP,SP,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,8.72,9350,maua,SP,utilidades_domesticas,500.0,19.0,8.0,13.0,maua,SP,1976.0,18.063837,0.007431,2.366493,6.062650
1,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,13.21,26.19,59296,sao goncalo do amarante,RN,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,27.20,31842,belo horizonte,MG,pet_shop,450.0,30.0,10.0,20.0,belo horizonte,MG,6000.0,1822.800366,0.012419,3.745833,9.450498
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2.87,12.11,9195,santo andre,SP,28.62,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,8.72,8752,mogi das cruzes,SP,papelaria,250.0,51.0,15.0,15.0,mogi das cruzes,SP,11475.0,30.174037,0.042940,0.893113,1.937824
3,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,16.54,22.09,86320,congonhinhas,PR,175.26,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,27.36,7112,guarulhos,SP,automotivo,7150.0,65.0,10.0,65.0,guarulhos,SP,42250.0,411.952997,0.009120,1.699896,14.833229
4,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,9.99,21.45,26525,nilopolis,RJ,75.16,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,15.17,12940,atibaia,SP,automotivo,50.0,16.0,16.0,17.0,atibaia,SP,4352.0,321.730402,0.008113,5.864988,4.116725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78110,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,22.19,23.46,11722,praia grande,SP,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,20.10,17602,tupa,SP,bebes,4950.0,40.0,10.0,40.0,tupa,SP,16000.0,474.098245,0.008090,1.425058,20.760579
78111,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,24.86,30.38,45920,nova vicosa,BA,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,65.02,8290,sao paulo,SP,eletrodomesticos_2,13300.0,32.0,90.0,22.0,sao paulo,SP,63360.0,968.051192,0.012188,1.241782,23.605451
78112,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,japuiba,RJ,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,370.146853,0.005486,3.749097,13.331840
78113,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,japuiba,RJ,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,370.146853,0.005486,3.749097,13.331840
78114,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,7.67,25.13,83750,lapa,PR,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,18.36,14407,franca,SP,beleza_saude,150.0,16.0,7.0,15.0,franca,SP,1680.0,631.817784,0.599282,0.452442,6.622581

In [27]:
df_treino = df_treino.drop_duplicates(subset=['order_id', 'product_id'])
display(df_treino)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days),customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes,approval_to_carrier_days,carrier_to_customer_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,8.44,15.54,3149,SP,SP,18.12,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,8.72,9350,maua,SP,utilidades_domesticas,500.0,19.0,8.0,13.0,maua,SP,1976.0,18.063837,0.007431,2.366493,6.062650
1,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,13.21,26.19,59296,sao goncalo do amarante,RN,72.20,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,27.20,31842,belo horizonte,MG,pet_shop,450.0,30.0,10.0,20.0,belo horizonte,MG,6000.0,1822.800366,0.012419,3.745833,9.450498
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2.87,12.11,9195,santo andre,SP,28.62,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,8.72,8752,mogi das cruzes,SP,papelaria,250.0,51.0,15.0,15.0,mogi das cruzes,SP,11475.0,30.174037,0.042940,0.893113,1.937824
3,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,16.54,22.09,86320,congonhinhas,PR,175.26,1,060cb19345d90064d1015407193c233d,8581055ce74af1daba164fdbd55a40de,2017-07-13 22:10:13,27.36,7112,guarulhos,SP,automotivo,7150.0,65.0,10.0,65.0,guarulhos,SP,42250.0,411.952997,0.009120,1.699896,14.833229
4,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,9.99,21.45,26525,nilopolis,RJ,75.16,1,4520766ec412348b8d4caa5e8a18c464,16090f2ca825584b5a147ab24aa30c86,2017-05-22 13:22:11,15.17,12940,atibaia,SP,automotivo,50.0,16.0,16.0,17.0,atibaia,SP,4352.0,321.730402,0.008113,5.864988,4.116725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78109,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,8.22,18.59,12209,são josé dos campos,SP,85.08,1,ac35486adb7b02598c182c2ff2e05254,e24fc9fcd865784fb25705606fe3dfe7,2017-03-15 09:54:05,13.08,12913,braganca paulista,SP,beleza_saude,1175.0,22.0,13.0,18.0,braganca paulista,SP,5148.0,69.481037,0.000000,1.058310,7.159699
78110,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,22.19,23.46,11722,praia grande,SP,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,20.10,17602,tupa,SP,bebes,4950.0,40.0,10.0,40.0,tupa,SP,16000.0,474.098245,0.008090,1.425058,20.760579
78111,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,24.86,30.38,45920,nova vicosa,BA,271.01,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,65.02,8290,sao paulo,SP,eletrodomesticos_2,13300.0,32.0,90.0,22.0,sao paulo,SP,63360.0,968.051192,0.012188,1.241782,23.605451
78112,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,17.09,37.11,28685,japuiba,RJ,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,40.59,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,370.146853,0.005486,3.749097,13.331840
78114,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,7.67,25.13,83750,lapa,PR,86.86,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,18.36,14407,franca,SP,beleza_saude,150.0,16.0,7.0,15.0,franca,SP,1680.0,631.817784,0.599282,0.452442,6.622581

In [28]:
df_treino = df_treino.sort_values(
    by=['order_id', 'distancia_km', 'purchase_to_approval_minutes', 'freight_value', 'product_volume'], 
    ascending=[False, False, False, False, False]
)

# Mantendo apenas a linha com os maiores valores por 'order_id'
df_treino = df_treino.groupby('order_id').first().reset_index()
display(df_treino)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days),customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes,approval_to_carrier_days,carrier_to_customer_days
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,7.61,15.63,28013,campos dos goytacazes,RJ,72.19,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,13.29,27277,volta redonda,SP,cool_stuff,650.0,28.0,9.0,14.0,volta redonda,RJ,3528.0,301.005664,0.032326,6.367141,1.214954
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,16.22,18.55,15775,santa fe do sul,SP,259.83,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,19.93,3471,sao paulo,SP,pet_shop,30000.0,50.0,30.0,40.0,sao paulo,SP,60000.0,589.274140,0.008414,8.145683,8.062083
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,7.95,21.39,35661,pará de minas,MG,216.87,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,17.87,37564,borda da mata,MG,moveis_decoracao,3050.0,33.0,13.0,33.0,borda da mata,MG,14157.0,312.495046,0.010405,1.908542,6.029491
3,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,25.11,40.42,13226,varzea paulista,SP,218.04,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,18.14,87900,loanda,PR,ferramentas_jardim,3750.0,35.0,40.0,30.0,loanda,PR,42000.0,646.221788,0.008588,11.816620,13.289144
4,00048cc3ae777c65dbb7d2a0634bc1ea,816cbea969fe5b689b39cfc97a506742,delivered,2017-05-15 21:42:34,2017-05-17 03:55:27,2017-05-17 11:05:55,2017-05-22 13:44:35,6.67,21.10,38017,uberaba,MG,34.59,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,12.69,14091,ribeirao preto,SP,utilidades_domesticas,450.0,24.0,8.0,15.0,ribeirao preto,SP,2880.0,161.597746,1.258947,0.298935,5.110185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68319,fffb0b1a50e65c449020434fa835e078,46b385c6d972b73cbcf797a8b16c072d,delivered,2017-04-12 16:35:43,2017-04-12 16:45:12,2017-04-27 09:26:54,2017-05-17 11:38:22,34.79,32.31,13083,campinas,SP,15.86,1,e7be84ea9462aac5e2b0b08eb35ba7f1,36a968b544695394e4e9d7572688598f,2017-04-28 16:45:12,10.96,11010,santos,SP,instrumentos_musicais,100.0,60.0,16.0,11.0,santos,SP,10560.0,146.589938,0.006586,14.695625,20.091296
68320,fffb2ef8874127f75b52b643880fd7e0,ca8374c00203cec663bc1eabf0aaede4,delivered,2018-03-30 15:36:49,2018-04-03 05:08:33,2018-04-03 15:12:19,2018-04-16 16:56:38,17.06,27.35,28540,cordeiro,RJ,39.96,1,ebceb9726cf5c6187b48e17fe58747b0,609e1a9a6c2539919b8205cf7c4e6ff0,2018-04-09 05:08:33,22.06,88359,brusque,SC,cama_mesa_banho,200.0,25.0,5.0,18.0,brusque,SC,2250.0,876.529078,3.563704,0.419282,13.072442
68321,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,21.12,30.30,56912,serra talhada,PE,356.76,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,34.19,24440,sao goncalo,RJ,relogios_presentes,350.0,16.0,14.0,11.0,sao goncalo,RJ,2464.0,1725.685456,0.420116,13.691597,7.006829
68322,fffce4705a9662cd70adb13d4a31832d,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,4.80,17.29,4039,sao paulo,SP,116.85,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,16.95,80610,curitiba,PR,esporte_lazer,967.0,21.0,24.0,19.0,curitiba,PR,9576.0,338.827218,1.004502,1.915845,1.881343
68323,fffe18544ffabc95dfada21779c9644f,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,1.96,10.04,13289,vinhedo,SP,64.71,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,8.72,4733,sao paulo,SP,informatica_acessorios,100.0,20.0,20.0,20.0,sao paulo,SP,8000.0,72.870476,0.042743,0.790521,1.122766

In [29]:
# Número de order_ids diferentes
num_order_ids = df_treino['order_id'].nunique()

print("Número de order_ids diferentes:", num_order_ids)

Número de order_ids diferentes: 68324

In [30]:
df_teste = pd.read_csv('FBase_Teste_Consolidada.csv')

In [31]:
pd.set_option('display.max_columns', None)
display(df_teste)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,caxias do sul,RS,144.31,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-05-07 15:24:08,25.31,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,1061.973738,0.027801
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,marilia,SP,62.00,1,5403528d987ad26e8d7cb25940411987,6560211a19b47992c3666cc44a7e94c0,2018-06-18 16:31:30,13.00,5849,sao paulo,SP,relogios_presentes,250.0,16.0,2.0,11.0,sao paulo,SP,352.0,366.092752,0.019734
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,barra do piraí,RJ,133.47,1,283dc451ad3918badb976d56ff887289,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-23 13:42:15,23.57,13405,piracicaba,SP,cama_mesa_banho,1650.0,44.0,2.0,35.0,piracicaba,SP,3080.0,394.192807,0.009271
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,promissao,SP,83.79,1,af893b2efa430418d774a852e7870601,8a432f4e5b471f8da497d7dc517666e2,2018-08-10 03:15:23,14.79,19042,presidente prudente,SP,utilidades_domesticas,1550.0,29.0,17.0,23.0,presidente prudente,SP,11339.0,169.959350,0.683519
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,lajeado,RS,164.80,1,6f3b5b605d91b7439c5e3f5a8dffeea7,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-02 15:30:29,18.90,14840,guariba,SP,relogios_presentes,335.0,17.0,11.0,16.0,guariba,SP,2992.0,975.175056,0.007188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32076,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,guaiba,RS,36.94,1,94a6c010ef78e62cab34c6caf0a69b5f,080102cd0a76b09e0dcf55fcacc60e05,2018-08-07 18:45:10,19.04,31140,belo horizonte,MG,consoles_games,100.0,20.0,3.0,15.0,belo horizonte,MG,900.0,1359.877613,0.009491
32077,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,rio de janeiro,RJ,199.00,1,7a10781637204d8d10485c71a6108a2e,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-04 13:30:47,0.00,14840,guariba,SP,relogios_presentes,342.0,18.0,13.0,15.0,guariba,SP,3510.0,533.938834,0.648229
32078,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,florianopolis,SC,123.69,1,2ff995aead9c63a1f37a07b3664ead37,8b9d6eec4a7eb7d0f9d579ce0b38324d,2018-05-18 13:57:03,34.69,26562,mesquita,RJ,moveis_sala,7500.0,61.0,11.0,46.0,mesquita,RJ,30866.0,725.631189,0.011910
32079,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,sao vicente,SP,714.35,1,26abb7e42cded69ba9b3736643ebeb39,4869f7a5dfa277a7dca6462dcf3b52b2,2018-06-22 04:16:51,18.45,14840,guariba,SP,relogios_presentes,867.0,20.0,7.0,14.0,guariba,SP,1960.0,347.434673,2.268912
32080,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,brasilia,DF,43.29,1,6157bc1be1e8edc531fc0c94dddf5ac9,ea8482cd71df3c1969d7b9473ff13abc,2018-08-06 21:45:29,15.30,4160,sao paulo,SP,telefonia,300.0,17.0,4.0,12.0,sao paulo,SP,816.0,874.394957,0.008507

In [32]:
df_teste = df_teste.drop_duplicates(subset=['order_id', 'product_id'])
display(df_teste)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes
0,6d5f4523e4747ceffd3e84b2d9bab9fc,15cae6030369d69f884089f8f746a272,2018-04-30 14:44:06,2018-04-30 15:24:08,95082,caxias do sul,RS,144.31,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-05-07 15:24:08,25.31,37175,ilicinea,MG,informatica_acessorios,6550.0,20.0,20.0,20.0,ilicinea,MG,8000.0,1061.973738,0.027801
1,02d2fbf1c9a20d04ceab86eb736fa22e,9befa54088a64c56bcba0c4328fdcd1d,2018-06-14 16:09:47,2018-06-14 16:38:12,17505,marilia,SP,62.00,1,5403528d987ad26e8d7cb25940411987,6560211a19b47992c3666cc44a7e94c0,2018-06-18 16:31:30,13.00,5849,sao paulo,SP,relogios_presentes,250.0,16.0,2.0,11.0,sao paulo,SP,352.0,366.092752,0.019734
2,dae91c4dced184f9ead8277e600b44a2,418e716dda4e353467a4f770a0bae939,2018-07-18 13:28:54,2018-07-18 13:42:15,27123,barra do piraí,RJ,133.47,1,283dc451ad3918badb976d56ff887289,da8622b14eb17ae2831f4ac5b9dab84a,2018-07-23 13:42:15,23.57,13405,piracicaba,SP,cama_mesa_banho,1650.0,44.0,2.0,35.0,piracicaba,SP,3080.0,394.192807,0.009271
3,9d138733c51598bbcd3ea81678facf91,5df2ff723d34c14ec65ed6d176c45eab,2018-08-07 10:51:07,2018-08-08 03:15:23,16370,promissao,SP,83.79,1,af893b2efa430418d774a852e7870601,8a432f4e5b471f8da497d7dc517666e2,2018-08-10 03:15:23,14.79,19042,presidente prudente,SP,utilidades_domesticas,1550.0,29.0,17.0,23.0,presidente prudente,SP,11339.0,169.959350,0.683519
4,e7666167df3a8011289e3980afcacf13,09d2d62001804e7ae2af3c29b13cb36c,2018-04-25 15:20:08,2018-04-25 15:30:29,95900,lajeado,RS,164.80,1,6f3b5b605d91b7439c5e3f5a8dffeea7,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-02 15:30:29,18.90,14840,guariba,SP,relogios_presentes,335.0,17.0,11.0,16.0,guariba,SP,2992.0,975.175056,0.007188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32076,95dda89c1cb224cddb6c5e1d81d4666c,b34d56bfad36d98cb3defe73359c7dea,2018-08-05 18:31:30,2018-08-05 18:45:10,92500,guaiba,RS,36.94,1,94a6c010ef78e62cab34c6caf0a69b5f,080102cd0a76b09e0dcf55fcacc60e05,2018-08-07 18:45:10,19.04,31140,belo horizonte,MG,consoles_games,100.0,20.0,3.0,15.0,belo horizonte,MG,900.0,1359.877613,0.009491
32077,577b745a85120419fe27073e3c9e1a76,dc5e8db48a49602f506e67b843668d72,2018-04-26 21:57:27,2018-04-27 13:30:54,22750,rio de janeiro,RJ,199.00,1,7a10781637204d8d10485c71a6108a2e,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-04 13:30:47,0.00,14840,guariba,SP,relogios_presentes,342.0,18.0,13.0,15.0,guariba,SP,3510.0,533.938834,0.648229
32078,527e7490ba8ede88db23aff0f080f5a7,5361c1b04541fb86bdb86deb42bf9d93,2018-05-14 13:39:54,2018-05-14 13:57:03,88060,florianopolis,SC,123.69,1,2ff995aead9c63a1f37a07b3664ead37,8b9d6eec4a7eb7d0f9d579ce0b38324d,2018-05-18 13:57:03,34.69,26562,mesquita,RJ,moveis_sala,7500.0,61.0,11.0,46.0,mesquita,RJ,30866.0,725.631189,0.011910
32079,d74cdf7dea16668a34d57964004f0e94,0d084e109d08dc18e40858b407ce7c6b,2018-06-16 21:49:37,2018-06-19 04:16:51,11320,sao vicente,SP,714.35,1,26abb7e42cded69ba9b3736643ebeb39,4869f7a5dfa277a7dca6462dcf3b52b2,2018-06-22 04:16:51,18.45,14840,guariba,SP,relogios_presentes,867.0,20.0,7.0,14.0,guariba,SP,1960.0,347.434673,2.268912
32080,16b0354e89f049afdd965c97e243dac6,ff891bcae7042cd5420f17811ab607d5,2018-08-03 21:33:14,2018-08-03 21:45:29,72301,brasilia,DF,43.29,1,6157bc1be1e8edc531fc0c94dddf5ac9,ea8482cd71df3c1969d7b9473ff13abc,2018-08-06 21:45:29,15.30,4160,sao paulo,SP,telefonia,300.0,17.0,4.0,12.0,sao paulo,SP,816.0,874.394957,0.008507

In [33]:
df_teste = df_teste.sort_values(
    by=['order_id', 'distancia_km', 'purchase_to_approval_minutes', 'freight_value', 'product_volume'], 
    ascending=[False, False, False, False, False]
)

# Mantendo apenas a linha com os maiores valores por 'order_id'
df_teste = df_teste.groupby('order_id').first().reset_index()
display(df_teste)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,customer_zip_code_prefix,geolocation_city_c,geolocation_state_c,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,freight_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_minutes
0,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08 10:00:35,2018-08-08 10:10:18,12952,atibaia,SP,25.78,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.79,14403,franca,SP,perfumaria,200.0,16.0,10.0,15.0,franca,SP,2400.0,301.951753,0.006748
1,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,2018-07-04 12:08:27,2018-07-05 16:35:48,11702,praia grande,SP,880.75,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,70.75,19010,presidente prudente,SP,ferramentas_jardim,13805.0,35.0,75.0,45.0,presidente prudente,SP,118125.0,547.472665,1.185660
2,0005f50442cb953dcd1d21e1fb923495,351d3cb2cee3c7fd0af6616c82df21d3,2018-07-02 13:59:39,2018-07-02 14:10:56,6636,jandira,SP,65.39,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,11.40,2274,sao paulo,SP,livros_tecnicos,850.0,29.0,3.0,21.0,sao paulo,SP,1827.0,33.159828,0.007836
3,00063b381e2406b52ad429470734ebd5,6a899e55865de6549a58d2c6845e5604,2018-07-27 17:21:27,2018-07-27 18:00:06,15910,monte alto,SP,57.98,1,f177554ea93259a5b282f24e33f65ab6,8602a61d680a10a82cceeeda0d99ea3d,2018-07-31 17:30:39,12.98,1001,sao paulo,SP,fashion_bolsas_e_acessorios,200.0,16.0,16.0,11.0,Sao Paulo,SP,2816.0,318.308071,0.026840
4,0006ec9db01a64e59a68b2c340bf65a7,5d178120c29c61748ea95bac23cb8f25,2018-07-24 17:04:17,2018-07-24 17:24:20,21810,rio de janeiro,RJ,97.32,1,99a4788cb24856965c36a24e339b6058,4a3ca9315b744ce9f8e9374361493884,2018-07-26 17:24:20,23.32,14940,ibitinga,SP,cama_mesa_banho,1383.0,50.0,10.0,40.0,ibitinga,SP,20000.0,566.124088,0.013924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28147,fff8286f77788ab8b55b2e5747fa7dd8,e79f494063c25f5c673222d8a2cc6f47,2018-07-03 21:53:22,2018-07-05 16:22:01,30881,belo horizonte,MG,40.27,1,a2da86fa759178e9e58e54aa1a144e59,ea8482cd71df3c1969d7b9473ff13abc,2018-07-05 22:31:13,15.28,4160,sao paulo,SP,telefonia,350.0,17.0,4.0,12.0,sao paulo,SP,816.0,493.164957,1.769896
28148,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,2018-06-19 09:27:48,2018-06-19 09:58:03,39401,montes claros,MG,139.88,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,20.03,13321,salto,SP,casa_construcao,1050.0,16.0,20.0,16.0,salto,SP,5120.0,806.546222,0.021007
28149,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,2018-04-23 13:57:06,2018-04-25 04:11:01,65077,sao luis,MA,343.40,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,43.41,88303,itajai,SC,utilidades_domesticas,10150.0,89.0,15.0,40.0,itajai,SC,53400.0,2755.314485,1.592998
28150,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,2018-07-14 10:26:46,2018-07-17 04:31:48,81690,curitiba,PR,386.53,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,36.53,1206,sao paulo,SP,informatica_acessorios,8950.0,45.0,26.0,38.0,Sao Paulo,SP,44460.0,354.848852,2.753495
28151,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,2018-06-09 17:00:18,2018-06-09 17:10:13,18605,botucatu,SP,55.79,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,12.79,14940,ibitinga,SP,cama_mesa_banho,600.0,30.0,3.0,19.0,ibitinga,SP,1710.0,133.230980,0.006887

In [34]:
df_teste.rename(columns={'purchase_to_approval_minutes': 'purchase_to_approval_days'}, inplace=True)
df_treino.rename(columns={'purchase_to_approval_minutes': 'purchase_to_approval_days'}, inplace=True)

In [35]:
# Removendo as colunas especificadas
df_treino = df_treino.drop(columns=[
    'customer_id',
    'order_status',
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'delivery_time_model (days)',
    'customer_zip_code_prefix',
    'order_item_id',
    'product_id',
    'seller_id',
    'shipping_limit_date',
    'seller_zip_code_prefix'
])

# Exibindo o DataFrame atualizado
display(df_treino)

,order_id,delivery_time (days),geolocation_city_c,geolocation_state_c,payment_value,freight_value,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_days,approval_to_carrier_days,carrier_to_customer_days
0,00010242fe8c5a6d1ba2dd792cb16214,7.61,campos dos goytacazes,RJ,72.19,13.29,volta redonda,SP,cool_stuff,650.0,28.0,9.0,14.0,volta redonda,RJ,3528.0,301.005664,0.032326,6.367141,1.214954
1,00018f77f2f0320c557190d7a144bdd3,16.22,santa fe do sul,SP,259.83,19.93,sao paulo,SP,pet_shop,30000.0,50.0,30.0,40.0,sao paulo,SP,60000.0,589.274140,0.008414,8.145683,8.062083
2,000229ec398224ef6ca0657da4fc703e,7.95,pará de minas,MG,216.87,17.87,borda da mata,MG,moveis_decoracao,3050.0,33.0,13.0,33.0,borda da mata,MG,14157.0,312.495046,0.010405,1.908542,6.029491
3,00042b26cf59d7ce69dfabb4e55b4fd9,25.11,varzea paulista,SP,218.04,18.14,loanda,PR,ferramentas_jardim,3750.0,35.0,40.0,30.0,loanda,PR,42000.0,646.221788,0.008588,11.816620,13.289144
4,00048cc3ae777c65dbb7d2a0634bc1ea,6.67,uberaba,MG,34.59,12.69,ribeirao preto,SP,utilidades_domesticas,450.0,24.0,8.0,15.0,ribeirao preto,SP,2880.0,161.597746,1.258947,0.298935,5.110185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68319,fffb0b1a50e65c449020434fa835e078,34.79,campinas,SP,15.86,10.96,santos,SP,instrumentos_musicais,100.0,60.0,16.0,11.0,santos,SP,10560.0,146.589938,0.006586,14.695625,20.091296
68320,fffb2ef8874127f75b52b643880fd7e0,17.06,cordeiro,RJ,39.96,22.06,brusque,SC,cama_mesa_banho,200.0,25.0,5.0,18.0,brusque,SC,2250.0,876.529078,3.563704,0.419282,13.072442
68321,fffb9224b6fc7c43ebb0904318b10b5f,21.12,serra talhada,PE,356.76,34.19,sao goncalo,RJ,relogios_presentes,350.0,16.0,14.0,11.0,sao goncalo,RJ,2464.0,1725.685456,0.420116,13.691597,7.006829
68322,fffce4705a9662cd70adb13d4a31832d,4.80,sao paulo,SP,116.85,16.95,curitiba,PR,esporte_lazer,967.0,21.0,24.0,19.0,curitiba,PR,9576.0,338.827218,1.004502,1.915845,1.881343
68323,fffe18544ffabc95dfada21779c9644f,1.96,vinhedo,SP,64.71,8.72,sao paulo,SP,informatica_acessorios,100.0,20.0,20.0,20.0,sao paulo,SP,8000.0,72.870476,0.042743,0.790521,1.122766

In [36]:
# Removendo as colunas especificadas
df_teste = df_teste.drop(columns=[
    'customer_id',
    'order_purchase_timestamp',
    'order_approved_at',
    'customer_zip_code_prefix',
    'order_item_id',
    'product_id',
    'seller_id',
    'shipping_limit_date',
    'seller_zip_code_prefix'
])

display(df_teste)

,order_id,geolocation_city_c,geolocation_state_c,payment_value,freight_value,seller_city,seller_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,geolocation_city_s,geolocation_state_s,product_volume,distancia_km,purchase_to_approval_days
0,00024acbcdf0a6daa1e931b038114c75,atibaia,SP,25.78,12.79,franca,SP,perfumaria,200.0,16.0,10.0,15.0,franca,SP,2400.0,301.951753,0.006748
1,000576fe39319847cbb9d288c5617fa6,praia grande,SP,880.75,70.75,presidente prudente,SP,ferramentas_jardim,13805.0,35.0,75.0,45.0,presidente prudente,SP,118125.0,547.472665,1.185660
2,0005f50442cb953dcd1d21e1fb923495,jandira,SP,65.39,11.40,sao paulo,SP,livros_tecnicos,850.0,29.0,3.0,21.0,sao paulo,SP,1827.0,33.159828,0.007836
3,00063b381e2406b52ad429470734ebd5,monte alto,SP,57.98,12.98,sao paulo,SP,fashion_bolsas_e_acessorios,200.0,16.0,16.0,11.0,Sao Paulo,SP,2816.0,318.308071,0.026840
4,0006ec9db01a64e59a68b2c340bf65a7,rio de janeiro,RJ,97.32,23.32,ibitinga,SP,cama_mesa_banho,1383.0,50.0,10.0,40.0,ibitinga,SP,20000.0,566.124088,0.013924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28147,fff8286f77788ab8b55b2e5747fa7dd8,belo horizonte,MG,40.27,15.28,sao paulo,SP,telefonia,350.0,17.0,4.0,12.0,sao paulo,SP,816.0,493.164957,1.769896
28148,fffbee3b5462987e66fb49b1c5411df2,montes claros,MG,139.88,20.03,salto,SP,casa_construcao,1050.0,16.0,20.0,16.0,salto,SP,5120.0,806.546222,0.021007
28149,fffc94f6ce00a00581880bf54a75a037,sao luis,MA,343.40,43.41,itajai,SC,utilidades_domesticas,10150.0,89.0,15.0,40.0,itajai,SC,53400.0,2755.314485,1.592998
28150,fffcd46ef2263f404302a634eb57f7eb,curitiba,PR,386.53,36.53,sao paulo,SP,informatica_acessorios,8950.0,45.0,26.0,38.0,Sao Paulo,SP,44460.0,354.848852,2.753495
28151,fffe41c64501cc87c801fd61db3f6244,botucatu,SP,55.79,12.79,ibitinga,SP,cama_mesa_banho,600.0,30.0,3.0,19.0,ibitinga,SP,1710.0,133.230980,0.006887

In [37]:
df_teste.to_csv('Teste_Final.csv', index=False)

In [38]:
df_treino.to_csv('Treino_Final.csv', index=False)